version: '3.8'

services:
  bore-server:
    build: .
    container_name: bore-server
    ports:
      - "7835:7835"  # Porta del server bore
      - "54000-54100:54000-54100"  # Range di porte per i tunnel
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    networks:
      - bore-network

networks:
  bore-network:
    driver: bridge